trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

# Se você tem .sln na raiz, mantenha; caso tenha um .csproj, aponte para ele.
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# PUBLICAÇÃO para uma pasta conhecida do pipeline
# Troque **/*.csproj pelo caminho exato do seu projeto, se preferir
- script: dotnet publish **/*.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish -> $(Build.ArtifactStagingDirectory)'

# Agora sim, publique o artefato da pasta produzida acima
- publish: $(Build.ArtifactStagingDirectory)
  artifact: WebApp
