trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Garante o SDK compatível com <TargetFramework>net6.0</TargetFramework>
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build -c $(buildConfiguration) --no-restore
  displayName: 'dotnet build'

- script: dotnet publish $(Build.SourcesDirectory)/pipelines-dotnet-core.csproj \
          -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish -> $(Build.ArtifactStagingDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: WebApp
